### ISSUE TITLE
'mwl-gauge' is not a known element

### ISSUE THREAD

**Issue by Piraban** [mattlewis92/angular-gauge#11]
I followed this site for reference but couldn't implement [https://www.npmjs.com/package/angular-gauge](URL)

imported `GaugeModule` 
`import { GaugeModule } from 'angular-gauge';`

[Angular]
'mwl-gauge' is not a known element:
1. If 'mwl-gauge' is an Angular component, then verify that it is part of this module.
2. If 'mwl-gauge' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

any solutions?

**Comment by mattlewis92** [comment]
The import should be `GaugeModule.forRoot()` not `GaugeModule`
