### ISSUE TITLE
Further component improvements

### ISSUE THREAD

**Issue by StefanoBettega** [mattlewis92/angular-gauge#2]
Hello, nice component. It would be great to have this kind of features added:

1. Usage in non square container
If you set dialStartAngle to180 and dialEndAngle to 0, gauge will stay on the top half of its container. If you downsize container's height, gauge will resize. Is there any way to make it not resizable?

2. Floating point support
Is there any way to set a gauge value to a floating point number (i.e. 10.5) and have it shown?

3. Min/Max values on dial and name/unit
It would be a nice improvement to add the min/max values on dial (with option to enable/disable them and customize font/size, ...) and optionally a measurement unit near gauge value

Thanks,
Stefano

**Comment by mattlewis92** [comment]
This component is only a tiny angular wrapper over https://github.com/naikus/svg-gauge, you'd be better off asking your questions there 😄
