### ISSUE TITLE
Dynamically change background color

### ISSUE THREAD

**Issue by pierrebiazotto** [mattlewis92/angular-gauge#3]
Hello,

Is it possible to change the background color dynamically? If not, is it planned to implement it? Or what could I do to implement it myself ? 

Thanks in advance,
Have a nice day.

**Comment by mattlewis92** [comment]
All styling is controlled via CSS, so you can just do `<mwl-gauge [style.backgroundColor]="bgColor"></mwl-gauge>`

**Comment by pierrebiazotto** [comment]
That's not what i'm talking about, i would just change the color of gauge. Ex : if the gauge is at 50% it's orange, 75% it's red, etc...

Thanks for your quick reply

**Comment by mattlewis92** [comment]
Ah right, you would need to dynamically add CSS classes to control this:
```
mwl-gauge.red > .gauge > .dial {
  stroke: red;
}

mwl-gauge.orange > .gauge > .dial {
  stroke: orange;
}
```

`<mwl-gauge [class.red]="value > 75" [class.orange]="value < 75 && value > 50"></mwl-gauge>`

**Comment by pierrebiazotto** [comment]
I'll try it this afternoon, I'll feedback you in the end afternoon. Thanks again.

**Comment by pierrebiazotto** [comment]
I don't use your idea, but it works. I prefer to inject class="myColor" which it change the stroke color.

Have a nice day.
