### ISSUE TITLE
Unable to get basic demo working

### ISSUE THREAD

**Issue by gitgraghu** [mattlewis92/angular-gauge#4]
Hi

I tried using this component. I followed the instruction as written in the README section.
However I am getting the below exception:

ERROR TypeError: label.call is not a function at updateGauge (gauge.js:275)
at Gauge (gauge.js:330)
at GaugeComponent.webpackJsonp.../../../../angular-gauge/gauge.component.js.GaugeComponent.ngAfterViewInit (gauge.component.js:33)

Please help. 

Thanks
Govind

**Comment by mattlewis92** [comment]
It sounds like the value you're passing to the `label` input isn't a function.
