### ISSUE TITLE
TypeError: label.call is not a function

### ISSUE THREAD

**Issue by sr0vk** [mattlewis92/angular-gauge#6]
Hi. I follow the instructions to include gauges in my project and get TypeError: label is not a function.
Also i try with the demo but get the same error:

TypeError: label.call is not a function. (In 'label.call(opts, theValue)', 'label.call' is undefined)
updateGauge — gauge.js:275
Gauge — gauge.js:330
ngAfterViewInit — gauge.component.js:33
callProviderLifecycles — core.es5.js:11161
callElementProvidersLifecycles — core.es5.js:11136
callLifecycleHooksChildrenFirst — core.es5.js:11120
checkAndUpdateView — core.es5.js:12152
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execEmbeddedViewsAction — core.es5.js:12465
checkAndUpdateView — core.es5.js:12145
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execEmbeddedViewsAction — core.es5.js:12465
checkAndUpdateView — core.es5.js:12145
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callViewAction — core.es5.js:12507
execEmbeddedViewsAction — core.es5.js:12465
checkAndUpdateView — core.es5.js:12145
callViewAction — core.es5.js:12507
execComponentViewsAction — core.es5.js:12439
checkAndUpdateView — core.es5.js:12150
callWithDebugContext — core.es5.js:13206
detectChanges — core.es5.js:10218
forEach
tick — core.es5.js:5075
(función anónima) — core.es5.js:4955:99
onInvoke — core.es5.js:4149
run — polyfills.js:3:4459
next — core.es5.js:4955
(función anónima) — core.es5.js:3851
__tryOrUnsub — Subscriber.js:238
next — Subscriber.js:185
_next — Subscriber.js:125
next — Subscriber.js:89
next — Subject.js:55
emit — core.es5.js:3837
checkStable — core.es5.js:4114
onLeave — core.es5.js:4190
onInvokeTask — core.es5.js:4143
runTask — polyfills.js:3:5154
invoke — polyfills.js:3:10953

What am i doing wrong?

Regards.
Pedro.

**Comment by mattlewis92** [comment]
Please see: https://github.com/mattlewis92/angular-gauge/issues/4#issuecomment-337849744
