### ISSUE TITLE
Get an error using your demo code.

### ISSUE THREAD

**Issue by iamcootis** [mattlewis92/angular-gauge#7]
I took your latest demo code and am coming up with these errors. I'm using the latest version of Angular and the gauge-svg code and chrome browser. Let me know if you need any more information. I am very new to angular and may not be of much help.

![capture2](https://user-images.githubusercontent.com/521754/31953409-bbd2856a-b8a8-11e7-90e9-72b25320b2a2.PNG)

![capture](https://user-images.githubusercontent.com/521754/31953403-b7281624-b8a8-11e7-8ca9-739292190302.PNG)

**Comment by ClaudeSutterlin** [comment]
Got the same. Tried the exact code from the demo to get the error to go away, but it still doesn't render a reasonable gauge.

**Comment by atecey** [comment]
Seeing the same issue.  Using Angular 5 with AOT turned on

**Comment by atecey** [comment]
Turns out label must be a function and it doesn't like it if its missing or anything else (string etc).  using the [demo code](https://github.com/mattlewis92/angular-gauge/blob/master/demo/demo.component.ts) should get it working

**Comment by prinzt** [comment]
@ClaudeSutterlin Check your installed version of svg-gauge.
svg-gauge introduced css breaking changes by a patch level update to v1.0.3 and angular-gauge relies on v1.0.2.
You need to do an explicit svg-gauge@1.0.2 install.

**Comment by mattlewis92** [comment]
So sorry about the late reply on this one, I don't have a lot of open source time nowadays. I've just published 2.0.1 which pins the version of svg-gauge to one without breaking changes. v3 will have it as a peer dependency so you have more control over the version yourself. Hope that helps! 😄
